using Jalium.UI.Documents;

namespace Jalium.UI.Controls.DevTools;

public partial class DevToolsWindow
{
    // ── Inspector element mutation: Delete / Undo ────────────────────────
    //
    // The inspector context menu can remove the selected element from the LIVE
    // visual tree and restore the most-recently-deleted one. Removal always goes
    // through the element's typed, public container API — Panel.Children,
    // Border.Child, Decorator.Child, ContentControl.Content — or, when the element
    // is a realized ItemsControl container, through the OWNING ITEMS COLLECTION
    // (Items / ItemsSource), never the items panel (which the generator would just
    // repopulate). For a templated ContentControl we route through the logical
    // ContentControl.Content rather than the template's ContentPresenter, so we do
    // not shadow a TemplateBinding with a local value. We never reach for the
    // protected Visual.AddVisualChild / RemoveVisualChild (they are inaccessible
    // from this assembly and bypass layout/z-order bookkeeping anyway).
    //
    // A single undo slot is kept — this is a diagnostics convenience, not a full
    // edit history — so deleting again replaces the slot. The deleted element is
    // intentionally kept alive by the record so it can be re-inserted.

    private ElementDeleteRecord? _deleteRecord;

    /// <summary>Carries enough state to restore one deleted element.</summary>
    private sealed class ElementDeleteRecord
    {
        public ElementDeleteRecord(string label, Func<UIElement?> restore)
        {
            Label = label;
            Restore = restore;
        }

        /// <summary>Type name of the deleted element, surfaced in the Undo label.</summary>
        public string Label { get; }

        /// <summary>
        /// Re-inserts the element through the same container API it was removed
        /// from and returns the <see cref="UIElement"/> to re-select afterwards, or
        /// <c>null</c> when a non-UIElement data item was restored (its container is
        /// regenerated by a later layout pass and is not a re-selectable element).
        /// </summary>
        public Func<UIElement?> Restore { get; }
    }

    private enum DeleteKind
    {
        None,
        PanelChild,
        BorderChild,
        DecoratorChild,
        ContentControlContent,
        ContentPresenterContent,
        ItemsControlItem,
    }

    /// <summary>
    /// True when <paramref name="target"/> can be removed from its container.
    /// <paramref name="reason"/> explains the refusal when this returns false so the
    /// menu item can show a disabled tooltip instead of failing silently on click.
    /// </summary>
    private bool CanDeleteElement(Visual target, out string reason)
        => ClassifyDeletion(target, out reason, out _) != DeleteKind.None;

    /// <summary>
    /// Classifies how (and whether) <paramref name="target"/> can be detached from
    /// its parent. Deliberately performs no mutation and captures no index — indices
    /// are read at the instant of deletion so a stale menu can never remove the
    /// wrong sibling.
    /// </summary>
    private DeleteKind ClassifyDeletion(Visual target, out string reason, out ItemsControl? itemsOwner)
    {
        reason = string.Empty;
        itemsOwner = null;

        if (target is not UIElement)
        {
            reason = "Only UI elements can be deleted.";
            return DeleteKind.None;
        }
        if (ReferenceEquals(target, _targetWindow))
        {
            reason = "Cannot delete the window root.";
            return DeleteKind.None;
        }

        // A realized ItemsControl container must be removed through its items
        // collection: pulling it out of the items panel is futile because the
        // control regenerates the container from the source on the next refresh.
        // This check runs first so an item container never falls into the Panel
        // branch (it lives directly inside the ItemsControl's items host).
        if (TryResolveItemContainer(target, out var owner, out _))
        {
            if (owner.ItemsSource == null || CanMutateItemsSource(owner.ItemsSource))
            {
                itemsOwner = owner;
                return DeleteKind.ItemsControlItem;
            }
            reason = "The bound item source is read-only or non-observable — remove the item in code.";
            return DeleteKind.None;
        }

        var parent = target.VisualParent;
        if (parent == null)
        {
            reason = "Element has no parent container.";
            return DeleteKind.None;
        }

        switch (parent)
        {
            case Panel:
                return DeleteKind.PanelChild;
            case Border border when ReferenceEquals(border.Child, target):
                return DeleteKind.BorderChild;
            case Decorator decorator when ReferenceEquals(decorator.Child, target):
                return DeleteKind.DecoratorChild;
            case ContentControl contentControl when ReferenceEquals(contentControl.Content, target):
                return DeleteKind.ContentControlContent;
            case ContentPresenter presenter when IsDeletableContentPresenterContent(presenter, target):
                return DeleteKind.ContentPresenterContent;
            default:
                reason = $"Parent '{parent.GetType().Name}' does not support element removal.";
                return DeleteKind.None;
        }
    }

    /// <summary>
    /// A ContentPresenter is deletable only when <paramref name="target"/> is the
    /// real content, not a wrapper the presenter generated for a string/data item
    /// (which would otherwise delete the whole underlying value). For a template
    /// part the logical owner is the templated <see cref="ContentControl"/>, so we
    /// match against that control's Content.
    /// </summary>
    private static bool IsDeletableContentPresenterContent(ContentPresenter presenter, Visual target)
    {
        // Template part of a templated ContentControl: the logical owner is that
        // control, so match (and later mutate) its Content rather than the presenter's.
        if (presenter.TemplatedParent is ContentControl owner)
            return ReferenceEquals(owner.Content, target);
        // Template part of some OTHER control: its Content is most likely a
        // TemplateBinding, and clearing it with a local value would shadow that
        // binding — refuse rather than corrupt the template.
        if (presenter.TemplatedParent != null)
            return false;
        // Standalone presenter the user authored directly: Content is a local value.
        return ReferenceEquals(presenter.Content, target);
    }

    /// <summary>
    /// True when an ItemsSource can be safely mutated AND the mutation will be
    /// reflected live: ItemsControl only re-syncs containers when the source raises
    /// collection-change notifications, so a writable-but-non-observable list (e.g.
    /// a plain <see cref="List{T}"/>) would mutate the data while the UI froze.
    /// </summary>
    private static bool CanMutateItemsSource(System.Collections.IEnumerable itemsSource)
        => itemsSource is System.Collections.IList { IsReadOnly: false, IsFixedSize: false }
           && itemsSource is System.Collections.Specialized.INotifyCollectionChanged;

    /// <summary>
    /// Resolves the owning <see cref="ItemsControl"/> and item index when
    /// <paramref name="element"/> is itself a realized item container (a DIRECT
    /// child of an ItemsControl's items host). A descendant inside an item template
    /// is deliberately NOT matched — it should remain deletable on its own rather
    /// than taking down the whole item.
    /// </summary>
    private static bool TryResolveItemContainer(Visual element, out ItemsControl owner, out int index)
    {
        owner = null!;
        index = -1;
        if (element is not UIElement container) return false;

        for (var ancestor = element.VisualParent; ancestor != null; ancestor = ancestor.VisualParent)
        {
            if (ancestor is not ItemsControl itemsControl) continue;

            var host = itemsControl.ItemsHostInternal;
            if (host == null || !ReferenceEquals(element.VisualParent, host)) continue;

            // The generator map is authoritative whenever it knows the container:
            // the virtualizing pipeline maps every realized child before adding it
            // to the host, so a realized container always resolves through it (and
            // a panel-child index there would be the wrong, window-relative index).
            // When the generator does NOT know the container, the host is populating
            // non-virtually — a plain panel, a VirtualizingPanel with
            // IsVirtualizing=false, or the legacy pipeline — and adds exactly one
            // container per item in source order, so the child index IS the item
            // index. (That equivalence assumes the host holds only item containers in
            // order, which is true for every current host; group headers/adorners
            // added directly to a virtualizing host would break it.)
            int resolved = itemsControl.ItemContainerGenerator.IndexFromContainer(container);
            if (resolved < 0)
                resolved = host.Children.IndexOf(container);

            if (resolved >= 0)
            {
                owner = itemsControl;
                index = resolved;
                return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Removes <paramref name="target"/> from the live visual tree (per
    /// <see cref="ClassifyDeletion"/>), records an undo entry, drops every inspector
    /// reference pinned to it, and rebuilds the tree. Always invoked through
    /// <see cref="Defer"/> so the context-menu popup is fully gone first.
    /// </summary>
    private void DeleteElement(Visual target)
    {
        var kind = ClassifyDeletion(target, out _, out var itemsOwner);
        if (kind == DeleteKind.None) return;
        if (target is not UIElement element) return;

        string label = target.GetType().Name;
        Func<UIElement?>? restore = null;

        switch (kind)
        {
            case DeleteKind.PanelChild:
            {
                if (element.VisualParent is not Panel panel) return;
                int slot = panel.Children.IndexOf(element);
                if (slot < 0) return;
                panel.Children.RemoveAt(slot);
                if (element.VisualParent != null) return; // removal did not take — bail without a record
                restore = () =>
                {
                    if (element.VisualParent != null) return null;
                    panel.Children.Insert(Math.Clamp(slot, 0, panel.Children.Count), element);
                    return element;
                };
                break;
            }
            case DeleteKind.BorderChild:
            {
                if (element.VisualParent is not Border border) return;
                border.Child = null;
                if (element.VisualParent != null) return;
                restore = () =>
                {
                    if (border.Child == null && element.VisualParent == null) border.Child = element;
                    return element;
                };
                break;
            }
            case DeleteKind.DecoratorChild:
            {
                if (element.VisualParent is not Decorator decorator) return;
                decorator.Child = null;
                if (element.VisualParent != null) return;
                restore = () =>
                {
                    if (decorator.Child == null && element.VisualParent == null) decorator.Child = element;
                    return element;
                };
                break;
            }
            case DeleteKind.ContentControlContent:
            {
                if (element.VisualParent is not ContentControl contentControl) return;
                object? saved = contentControl.Content;
                contentControl.Content = null;
                if (element.VisualParent != null) return;
                restore = () =>
                {
                    if (contentControl.Content == null) contentControl.Content = saved;
                    return saved as UIElement;
                };
                break;
            }
            case DeleteKind.ContentPresenterContent:
            {
                if (element.VisualParent is not ContentPresenter presenter) return;

                // Prefer the logical owner of a template part so the deletion (and
                // its undo) flow through the TemplateBinding instead of pinning a
                // local value onto a template-internal presenter.
                if (presenter.TemplatedParent is ContentControl owner && ReferenceEquals(owner.Content, target))
                {
                    object? saved = owner.Content;
                    owner.Content = null;
                    if (element.VisualParent != null) return;
                    restore = () =>
                    {
                        if (owner.Content == null) owner.Content = saved;
                        return saved as UIElement;
                    };
                }
                else if (presenter.TemplatedParent == null && ReferenceEquals(presenter.Content, target))
                {
                    object? saved = presenter.Content;
                    presenter.Content = null;
                    if (element.VisualParent != null) return;
                    restore = () =>
                    {
                        if (presenter.Content == null) presenter.Content = saved;
                        return saved as UIElement;
                    };
                }
                else
                {
                    return;
                }
                break;
            }
            case DeleteKind.ItemsControlItem:
            {
                var owner = itemsOwner;
                if (owner == null) return;
                // Re-resolve the index at execution time — the menu may have been
                // open while the collection changed underneath it.
                if (!TryResolveItemContainer(target, out _, out int itemIndex)) return;

                if (owner.ItemsSource == null)
                {
                    if (itemIndex < 0 || itemIndex >= owner.Items.Count) return;
                    object data = owner.Items[itemIndex]!;
                    owner.Items.RemoveAt(itemIndex);
                    restore = () =>
                    {
                        owner.Items.Insert(Math.Clamp(itemIndex, 0, owner.Items.Count), data);
                        // Own-container items (a UIElement added straight to Items) can be
                        // re-selected; a virtualizing host re-realizes on the next layout, so
                        // the VisualParent guard in UndoDelete simply skips reveal there.
                        return data as UIElement;
                    };
                }
                else if (CanMutateItemsSource(owner.ItemsSource) && owner.ItemsSource is System.Collections.IList list)
                {
                    if (itemIndex < 0 || itemIndex >= list.Count) return;
                    object data = list[itemIndex]!;
                    list.RemoveAt(itemIndex);
                    restore = () =>
                    {
                        list.Insert(Math.Clamp(itemIndex, 0, list.Count), data);
                        return data as UIElement;
                    };
                }
                else
                {
                    return;
                }
                break;
            }
        }

        if (restore == null) return;

        _deleteRecord = new ElementDeleteRecord(label, restore);

        // The right-click handler selected `target` before opening the menu, so it
        // is the current selection. Drop every reference to the now-detached element
        // before rebuilding so no stale amber highlight or property row survives the
        // refresh.
        if (ReferenceEquals(_selectedVisual, target))
        {
            _selectedVisual = null;
            _overlay?.HighlightElement(null);
            UpdatePropertiesPanel(null);
        }

        RefreshVisualTree();
    }

    /// <summary>
    /// Restores the most-recently-deleted element and re-selects it. Invoked through
    /// <see cref="Defer"/>. The undo slot is consumed whether or not the re-insertion
    /// finds a valid slot, so a failed restore cannot loop.
    /// </summary>
    private void UndoDelete()
    {
        var record = _deleteRecord;
        _deleteRecord = null;
        if (record == null) return;

        UIElement? revealed = record.Restore();
        RefreshVisualTree();

        if (revealed != null && revealed.VisualParent != null)
            RevealInInspector(revealed);
    }
}
