# Regenerates the Vulkan Vello compute SPIR-V from the canonical D3D12 HLSL
# source (../../jalium.native.d3d12/shaders/vello_*.cs.hlsl + vello_shared.hlsli)
# and embeds it into ../include/vulkan_vello_shaders.h.
#
# Layout strategy: -fvk-use-dx-layout makes every StructuredBuffer stride
# byte-match the C++ structs in d3d12_vello.h (single source of truth). This
# REQUIRES VK_EXT_scalar_block_layout at runtime (probed + graceful fallback in
# vulkan_render_target.cpp). Register-class shifts map HLSL b/t/s/u space0 to
# non-colliding Vulkan bindings: b->N, t->N+16, s->N+32, u->N+48 (matches
# vulkan_shader_compiler.h convention).
#
# Usage:  pwsh ./gen_vello_spv.ps1   (run from anywhere; paths are script-relative)

param(
    [string]$ShaderSrcDir = (Join-Path $PSScriptRoot '..\..\jalium.native.d3d12\shaders'),
    [string]$SpvOutDir    = (Join-Path $PSScriptRoot 'vello_spv'),
    [string]$HeaderPath   = (Join-Path $PSScriptRoot '..\include\vulkan_vello_shaders.h')
)

$ErrorActionPreference = 'Stop'

# Resolve dxc.exe: prefer the Vulkan SDK, else PATH.
$dxc = $null
if ($env:VULKAN_SDK -and (Test-Path (Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'))) {
    $dxc = Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'
} else {
    $cmd = Get-Command dxc -ErrorAction SilentlyContinue
    if ($cmd) { $dxc = $cmd.Source }
}
if (-not $dxc) { throw "dxc.exe not found (set VULKAN_SDK or put dxc on PATH)" }
Write-Host "Using dxc: $dxc"

# The 13 Vello compute stages (file base names, no extension).
$stages = @(
    'vello_backdrop',
    'vello_bbox_clear',
    'vello_binning',
    'vello_clip_leaf',
    'vello_clip_reduce',
    'vello_coarse',
    'vello_fine',
    'vello_flatten',
    'vello_path_count',
    'vello_path_count_setup',
    'vello_path_tiling',
    'vello_path_tiling_setup',
    'vello_tile_alloc'
)

if (-not (Test-Path $SpvOutDir)) { New-Item -ItemType Directory -Path $SpvOutDir | Out-Null }

# snake_case stage -> PascalCase symbol fragment, dropping the leading 'vello'.
function To-Symbol([string]$stage) {
    $parts = $stage.Split('_') | Where-Object { $_ -ne 'vello' }
    ($parts | ForEach-Object { $_.Substring(0,1).ToUpper() + $_.Substring(1) }) -join ''
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// Auto-generated Vello compute SPIR-V bytecode (cs_6_0).')
[void]$sb.AppendLine('// Generated by shaders/gen_vello_spv.ps1 - do not edit manually.')
[void]$sb.AppendLine('// Source of truth: jalium.native.d3d12/shaders/vello_*.cs.hlsl + vello_shared.hlsli.')
[void]$sb.AppendLine('// Compiled with -fvk-use-dx-layout (requires VK_EXT_scalar_block_layout at runtime)')
[void]$sb.AppendLine('// and register shifts b->N, t->N+16, s->N+32, u->N+48.')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include <cstddef>')
[void]$sb.AppendLine('#include <cstdint>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace jalium {')

foreach ($stage in $stages) {
    $src = Join-Path $ShaderSrcDir "$stage.cs.hlsl"
    if (-not (Test-Path $src)) { throw "Missing shader source: $src" }
    $spv = Join-Path $SpvOutDir "$stage.spv"

    Write-Host "Compiling $stage.cs.hlsl -> $stage.spv"
    & $dxc -spirv -T cs_6_0 -E main `
        -fvk-t-shift 16 0 -fvk-s-shift 32 0 -fvk-u-shift 48 0 `
        -fvk-use-dx-layout -O3 `
        -I $ShaderSrcDir $src -Fo $spv
    if ($LASTEXITCODE -ne 0) { throw "dxc failed for $stage (exit $LASTEXITCODE)" }

    $bytes = [System.IO.File]::ReadAllBytes($spv)
    if (($bytes.Length % 4) -ne 0) { throw "$stage.spv length $($bytes.Length) not a multiple of 4" }
    $wordCount = $bytes.Length / 4

    $sym = 'kVello' + (To-Symbol $stage) + 'Spv'

    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("// $stage.spv ($($bytes.Length) bytes)")
    [void]$sb.AppendLine("inline constexpr uint32_t ${sym}[] = {")

    $line = '    '
    for ($w = 0; $w -lt $wordCount; $w++) {
        $i = $w * 4
        $word = [uint32]$bytes[$i] -bor ([uint32]$bytes[$i+1] -shl 8) -bor ([uint32]$bytes[$i+2] -shl 16) -bor ([uint32]$bytes[$i+3] -shl 24)
        $line += ('0x{0:x8}u,' -f $word)
        if ((($w + 1) % 8) -eq 0) {
            [void]$sb.AppendLine($line)
            $line = '    '
        } else {
            $line += ' '
        }
    }
    if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line.TrimEnd()) }
    [void]$sb.AppendLine('};')
    [void]$sb.AppendLine("inline constexpr size_t ${sym}Size = sizeof(${sym});")
}

[void]$sb.AppendLine('')
[void]$sb.AppendLine('} // namespace jalium')

[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
$hdrLen = [System.IO.FileInfo]::new($HeaderPath).Length
Write-Host "Generated $HeaderPath ($hdrLen bytes)"
