# Compiles the engine-batch VS/FS (impeller_solid_fill.{vert,frag}.hlsl) to
# SPIR-V and regenerates ../include/vulkan_impeller_shaders.h wholesale (the
# header only holds this one shader pair — same regenerate-the-file pattern as
# gen_text_glyph_spv.ps1). Both shaders use [[vk::push_constant]], so DXC
# -spirv is the only valid compiler.

param(
    [string]$ShaderSrcDir = $PSScriptRoot,
    [string]$HeaderPath   = (Join-Path $PSScriptRoot '..\include\vulkan_impeller_shaders.h')
)

$ErrorActionPreference = 'Stop'

$dxc = $null
if ($env:VULKAN_SDK -and (Test-Path (Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'))) {
    $dxc = Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'
} else {
    $cmd = Get-Command dxc -ErrorAction SilentlyContinue
    if ($cmd) { $dxc = $cmd.Source }
}
if (-not $dxc) { throw "dxc.exe not found (set VULKAN_SDK or put dxc on PATH)" }

function Compile-Spv([string]$src, [string]$profile) {
    $tmp = [System.IO.Path]::GetTempFileName() + '.spv'
    & $dxc -spirv -T $profile -E main -O3 $src -Fo $tmp | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "dxc failed for $src" }
    $bytes = [System.IO.File]::ReadAllBytes($tmp)
    Remove-Item $tmp -Force
    return ,$bytes
}

function Emit-Array([System.Text.StringBuilder]$sb, [string]$sym, [string]$comment, [byte[]]$bytes) {
    if (($bytes.Length % 4) -ne 0) { throw "$sym length not multiple of 4" }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine(("// {0} ({1} bytes)" -f $comment, $bytes.Length))
    [void]$sb.AppendLine("inline constexpr uint32_t ${sym}[] = {")
    $words = $bytes.Length / 4
    $line = '    '
    for ($w = 0; $w -lt $words; $w++) {
        $i = $w * 4
        $word = [uint32]$bytes[$i] -bor ([uint32]$bytes[$i+1] -shl 8) -bor ([uint32]$bytes[$i+2] -shl 16) -bor ([uint32]$bytes[$i+3] -shl 24)
        $line += ('0x{0:x8}u,' -f $word)
        if ((($w + 1) % 8) -eq 0) { [void]$sb.AppendLine($line); $line = '    ' } else { $line += ' ' }
    }
    if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line.TrimEnd()) }
    [void]$sb.AppendLine('};')
    [void]$sb.AppendLine("inline constexpr size_t ${sym}Size = sizeof(${sym});")
}

$vs = Compile-Spv (Join-Path $ShaderSrcDir 'impeller_solid_fill.vert.hlsl') 'vs_6_0'
$fs = Compile-Spv (Join-Path $ShaderSrcDir 'impeller_solid_fill.frag.hlsl') 'ps_6_0'

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include <cstddef>')
[void]$sb.AppendLine('#include <cstdint>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace jalium {')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// ============================================================================')
[void]$sb.AppendLine('// Embedded SPIR-V shaders for the engine-batch pipelines (ImpellerVulkanEngine')
[void]$sb.AppendLine('// / VelloVulkanEngine CPU-tessellation batches + the stencil-then-cover PSOs).')
[void]$sb.AppendLine('// Auto-generated by shaders/gen_impeller_solid_fill_spv.ps1 - do not edit')
[void]$sb.AppendLine('// manually; edit impeller_solid_fill.{vert,frag}.hlsl and re-run the script.')
[void]$sb.AppendLine('//')
[void]$sb.AppendLine('// Push-constant block = EngineBatchPushConstants (vulkan_render_target.cpp):')
[void]$sb.AppendLine('//   VS: position = mvp * vec4(pos, 0, 1); passthrough color.')
[void]$sb.AppendLine('//   FS: vertex color (premultiplied) x per-batch rounded-clip SDF coverage.')
[void]$sb.AppendLine('// ============================================================================')
Emit-Array $sb 'kImpellerSolidFillVertShaderSpv' 'impeller_solid_fill.vert.spv' $vs
Emit-Array $sb 'kImpellerSolidFillFragShaderSpv' 'impeller_solid_fill.frag.spv' $fs
[void]$sb.AppendLine('')
[void]$sb.AppendLine('} // namespace jalium')

[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
Write-Host ("Generated {0}  (vert={1}B frag={2}B)" -f $HeaderPath, $vs.Length, $fs.Length)

# Refresh the sibling .spv artifacts too, so the standalone files next to the
# HLSL sources never go stale relative to the embedded header.
[System.IO.File]::WriteAllBytes((Join-Path $ShaderSrcDir 'impeller_solid_fill.vert.spv'), $vs)
[System.IO.File]::WriteAllBytes((Join-Path $ShaderSrcDir 'impeller_solid_fill.frag.spv'), $fs)
Write-Host "Refreshed impeller_solid_fill.{vert,frag}.spv artifacts"
