# Compiles the dual-source LCD coverage variant of bitmap_quad.frag.hlsl and
# embeds it into ../include/vulkan_bitmap_lcd_shaders.h. The pipeline reuses
# the normal bitmap quad vertex shader and descriptor/push-constant layout.

param(
    [string]$ShaderSrcDir = $PSScriptRoot,
    [string]$HeaderPath = (Join-Path $PSScriptRoot '..\include\vulkan_bitmap_lcd_shaders.h')
)

$ErrorActionPreference = 'Stop'

$dxc = $null
if ($env:VULKAN_SDK -and (Test-Path (Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'))) {
    $dxc = Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'
} else {
    $cmd = Get-Command dxc -ErrorAction SilentlyContinue
    if ($cmd) { $dxc = $cmd.Source }
}
if (-not $dxc) { throw 'dxc.exe not found (set VULKAN_SDK or put dxc on PATH)' }

$tmp = [System.IO.Path]::GetTempFileName() + '.spv'
& $dxc -spirv -T ps_6_0 -E main -O3 -D JALIUM_LCD_COVERAGE=1 `
    (Join-Path $ShaderSrcDir 'bitmap_quad.frag.hlsl') -Fo $tmp | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'dxc failed for bitmap LCD coverage shader' }
$bytes = [System.IO.File]::ReadAllBytes($tmp)
Remove-Item $tmp -Force
if (($bytes.Length % 4) -ne 0) { throw 'SPIR-V length is not a multiple of four' }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// Auto-generated by shaders/gen_bitmap_lcd_spv.ps1 - do not edit manually.')
[void]$sb.AppendLine('// Dual-source LCD coverage bitmap fragment shader.')
[void]$sb.AppendLine('#include <cstddef>')
[void]$sb.AppendLine('#include <cstdint>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace jalium {')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('inline constexpr uint32_t kBitmapQuadLcdFragSpv[] = {')
$line = '    '
for ($wordIndex = 0; $wordIndex -lt ($bytes.Length / 4); $wordIndex++) {
    $offset = $wordIndex * 4
    $word = [uint32]$bytes[$offset] -bor
            ([uint32]$bytes[$offset + 1] -shl 8) -bor
            ([uint32]$bytes[$offset + 2] -shl 16) -bor
            ([uint32]$bytes[$offset + 3] -shl 24)
    $line += ('0x{0:x8}u,' -f $word)
    if ((($wordIndex + 1) % 8) -eq 0) {
        [void]$sb.AppendLine($line)
        $line = '    '
    } else {
        $line += ' '
    }
}
if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line.TrimEnd()) }
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('inline constexpr size_t kBitmapQuadLcdFragSpvSize = sizeof(kBitmapQuadLcdFragSpv);')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('} // namespace jalium')

[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
Write-Host "Generated $HeaderPath ($($bytes.Length) bytes SPIR-V)"
