# Compiles the dedicated text-glyph VS/FS (text_glyph.{vert,frag}.hlsl) to SPIR-V
# and embeds them into ../include/vulkan_text_glyph_shaders.h. Both shaders use
# explicit [[vk::binding]] so no register-class shift is required.

param(
    [string]$ShaderSrcDir = $PSScriptRoot,
    [string]$HeaderPath   = (Join-Path $PSScriptRoot '..\include\vulkan_text_glyph_shaders.h')
)

$ErrorActionPreference = 'Stop'

$dxc = $null
if ($env:VULKAN_SDK -and (Test-Path (Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'))) {
    $dxc = Join-Path $env:VULKAN_SDK 'Bin\dxc.exe'
} else {
    $cmd = Get-Command dxc -ErrorAction SilentlyContinue
    if ($cmd) { $dxc = $cmd.Source }
}
if (-not $dxc) { throw "dxc.exe not found (set VULKAN_SDK or put dxc on PATH)" }

function Compile-Spv([string]$src, [string]$profile, [string[]]$defines = @()) {
    $tmp = [System.IO.Path]::GetTempFileName() + '.spv'
    $defineArgs = @($defines | ForEach-Object { "-D$_" })
    & $dxc -spirv -T $profile -E main -O3 @defineArgs $src -Fo $tmp | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "dxc failed for $src" }
    $bytes = [System.IO.File]::ReadAllBytes($tmp)
    Remove-Item $tmp -Force
    return ,$bytes
}

function Emit-Array([System.Text.StringBuilder]$sb, [string]$sym, [byte[]]$bytes) {
    if (($bytes.Length % 4) -ne 0) { throw "$sym length not multiple of 4" }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("inline constexpr uint32_t ${sym}[] = {")
    $words = $bytes.Length / 4
    $line = '    '
    for ($w = 0; $w -lt $words; $w++) {
        $i = $w * 4
        $word = [uint32]$bytes[$i] -bor ([uint32]$bytes[$i+1] -shl 8) -bor ([uint32]$bytes[$i+2] -shl 16) -bor ([uint32]$bytes[$i+3] -shl 24)
        $line += ('0x{0:x8}u,' -f $word)
        if ((($w + 1) % 8) -eq 0) { [void]$sb.AppendLine($line); $line = '    ' } else { $line += ' ' }
    }
    if ($line.Trim().Length -gt 0) { [void]$sb.AppendLine($line.TrimEnd()) }
    [void]$sb.AppendLine('};')
    [void]$sb.AppendLine("inline constexpr size_t ${sym}Size = sizeof(${sym});")
}

$vs = Compile-Spv (Join-Path $ShaderSrcDir 'text_glyph.vert.hlsl') 'vs_6_0'
# Grayscale FS (default): single SV_Target0 output for the one-attachment text
# pipeline. ClearType FS (JALIUM_CLEARTYPE): dual-source output with SV_Target0 /
# SV_Target1 pinned to Location 0, Index 0/1 — the layout Vulkan's *_SRC1_*
# blend factors read; a bare SV_Target1 would land at Location 1 and never
# feed the dual-source blend.
$fs = Compile-Spv (Join-Path $ShaderSrcDir 'text_glyph.frag.hlsl') 'ps_6_0'
$fsClearType = Compile-Spv (Join-Path $ShaderSrcDir 'text_glyph.frag.hlsl') 'ps_6_0' @('JALIUM_CLEARTYPE=1')

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('// Auto-generated by shaders/gen_text_glyph_spv.ps1 - do not edit manually.')
[void]$sb.AppendLine('// Dedicated text-glyph VS/FS (per-glyph SSBO instancing + atlas coverage sample).')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('#include <cstddef>')
[void]$sb.AppendLine('#include <cstdint>')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('namespace jalium {')
Emit-Array $sb 'kTextGlyphVertSpv' $vs
Emit-Array $sb 'kTextGlyphFragSpv' $fs
Emit-Array $sb 'kTextGlyphFragClearTypeSpv' $fsClearType
[void]$sb.AppendLine('')
[void]$sb.AppendLine('} // namespace jalium')

[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
Write-Host "Generated $HeaderPath"
