using System.Globalization;
using System.Text;
using System.Text.Json;
using Jalium.UI.Styling;

namespace Jalium.UI.Compiler;

internal sealed record CssCompilationEntry(string Key, CssStyleSheet Sheet, bool Resource, bool Inline = false);

/// <summary>Emits the runtime parser's actual object graph, preserving shared nesting/scope nodes.</summary>
internal sealed class CssSourceEmitter
{
    private readonly StringBuilder _source = new();
    private readonly Dictionary<object, string> _nodes = new(ReferenceEqualityComparer.Instance);
    private readonly HashSet<object> _active = new(ReferenceEqualityComparer.Instance);
    private readonly Dictionary<string, string> _anonymous = new(StringComparer.Ordinal);

    internal static string Generate(IReadOnlyList<CssCompilationEntry> entries)
    {
        var output = new StringBuilder("// <auto-generated/>\n#nullable enable\n");
        output.Append("namespace Jalium.UI.Generated;\ninternal static class __JaliumCompiledCss\n{\n");
        output.Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]\n    internal static void Register()\n    {\n");
        output.Append("        var assembly = typeof(__JaliumCompiledCss).Assembly;\n");
        for (var i = 0; i < entries.Count; i++)
        {
            var entry = entries[i];
            var registration = entry.Resource
                ? $"RegisterResource(assembly, {Quote(entry.Key)}, Create{i})"
                : $"RegisterText(assembly, {Quote(entry.Key)}, {Bool(entry.Inline)}, Create{i})";
            output.Append($"        global::Jalium.UI.Styling.CssCompiledStyleRegistry.{registration};\n");
        }
        output.Append("    }\n");
        for (var i = 0; i < entries.Count; i++)
        {
            output.Append($"\n    internal static global::Jalium.UI.Styling.CssStyleSheet Create{i}(string? sourceLabel, global::System.Uri? baseUri)\n    {{\n");
            output.Append("        var b = new global::Jalium.UI.Styling.CssStyleSheetBuilder(1);\n");
            output.Append(new CssSourceEmitter().Emit(entries[i].Sheet));
            output.Append("        return b.Build(sourceLabel, baseUri);\n    }\n");
        }
        output.Append("}\n");
        return output.ToString();
    }

    private string Emit(CssStyleSheet sheet)
    {
        foreach (var rule in sheet.Rules)
            Line($"b.Rule({Nodes(rule.Selectors)}, {Nodes(rule.Declarations)}, {Node(rule.Condition)}, {LayerName(rule.LayerName)}, {Node(rule.Scope)});");
        foreach (var layer in sheet.Layers)
            Line($"b.Layer({LayerName(layer.Name)}, {Number(layer.Offset)}, {Node(layer.Condition)}, {Bool(layer.Anonymous)});");
        foreach (var import in sheet.Imports)
            Line($"b.Import({Quote(import.Reference)}, {Number(import.Line)}, {Number(import.Offset)}, {LayerName(import.LayerName)}, {Bool(import.AnonymousLayer)}, {Node(import.Supports)}, {Node(import.Media)});");
        foreach (var property in sheet.Properties)
        {
            var syntax = property.Syntax;
            Line($"b.Property({Quote(property.Name)}, {Array(syntax.Components.Select(c => Quote(c.Name)))}, " +
                $"{Array(syntax.Components.Select(c => Bool(c.Type)))}, {Array(syntax.Components.Select(c => "(char)" + Number(c.Multiplier)))}, " +
                $"{Bool(syntax.Universal)}, {Bool(property.Inherits)}, {Quote(property.InitialValue)}, {Number(property.Offset)}, {Node(property.Condition)}, {LayerName(property.LayerName)});");
        }
        foreach (var diagnostic in sheet.Diagnostics)
            Line($"b.Diagnostic({Number((byte)diagnostic.Severity)}, {Quote(diagnostic.Message)}, {Number(diagnostic.Line)});");
        return _source.ToString();
    }

    private string Node(object? node)
    {
        if (node is null) return "-1";
        if (_nodes.TryGetValue(node, out var existing)) return existing;
        if (!_active.Add(node)) throw new InvalidOperationException("Cyclic compiled CSS syntax graph.");
        var expression = node switch
        {
            CssDeclaration d => $"Declaration({Quote(d.PropertyName)}, {Quote(d.RawValue)}, {Bool(d.Important)})",
            CssAttributeSelector a => $"Attribute({Quote(a.Name)}, {Quote(a.Operator)}, {Quote(a.Value)}, {Bool(a.IgnoreCase)}, {Quote(a.NamespaceUri)})",
            CssFunctionalPseudo f => $"Function({Quote(f.Name)}, {Nodes(f.Selectors)}, {Number(f.A)}, {Number(f.B)}, {Node(f.NestingScope)})",
            CssCompound c => $"Compound({Quote(c.TypeName)}, {Bool(c.Universal)}, {Quote(c.NamespaceUri)}, " +
                $"{Bool(c.ExpandedTypeName)}, {Bool(c.ExplicitTypeSelector)}, {Bool(c.DefaultNamespaceApplied)}, {Quote(c.Id)}, " +
                $"{(c.Classes is null ? "null" : Array(c.Classes.Select(Quote)))}, " +
                $"{(c.Pseudos is null ? "null" : Array(c.Pseudos.Select(p => Number((byte)p))))}, {Number((ushort)c.StateMask)}, {Nodes(c.Attributes)}, {Nodes(c.Functions)})",
            CssSelector s => $"Selector({Nodes(s.Compounds)}, {Array(s.Combinators.Select(c => Number((byte)c)))}, " +
                $"{Number(s.Specificity)}, {Number((ushort)s.RightmostStates)}, {Number((ushort)s.AncestorStates)}, {Bool(s.ContainsNesting)}, {Bool(s.ContainsScope)})",
            CssScopeRule s => $"Scope({Nodes(s.Starts)}, {Nodes(s.Limits)}, {Node(s.Parent)})",
            CssCondition c => $"Condition({Quote(c.Kind)}, {Quote(c.Query)}, {Node(c.Left)}, {Node(c.Right)}, {Node(c.Namespaces)})",
            CssNamespaceContext n => Namespace(n),
            _ => throw new NotSupportedException($"Unsupported CSS syntax node {node.GetType().Name}."),
        };
        var name = "n" + Number(_nodes.Count);
        _nodes.Add(node, name);
        _active.Remove(node);
        Line($"var {name} = b.{expression};");
        return name;
    }

    private static string Namespace(CssNamespaceContext context)
    {
        var prefixes = context.Prefixes.OrderBy(p => p.Key, StringComparer.Ordinal).ToArray();
        return $"Namespaces({Quote(context.DefaultNamespace)}, {Array(prefixes.Select(p => Quote(p.Key)))}, {Array(prefixes.Select(p => Quote(p.Value)))})";
    }

    private string LayerName(string? name)
    {
        if (name is null) return "null";
        var parts = name.Split('.');
        if (!parts.Any(p => p.StartsWith("#anonymous-", StringComparison.Ordinal))) return Quote(name);
        return string.Join(" + \".\" + ", parts.Select(part =>
        {
            if (!part.StartsWith("#anonymous-", StringComparison.Ordinal)) return Quote(part);
            if (_anonymous.TryGetValue(part, out var existing)) return existing;
            var variable = "layer" + Number(_anonymous.Count);
            _anonymous.Add(part, variable);
            Line($"var {variable} = b.AnonymousLayer();");
            return variable;
        }));
    }

    private string Nodes<T>(IEnumerable<T>? nodes) where T : class
        => nodes is null ? "null" : Array(nodes.Select(node => Node(node)));
    private static string Array(IEnumerable<string> items) => "[" + string.Join(", ", items) + "]";
    private static string Bool(bool value) => value ? "true" : "false";
    private static string Number(int value) => value.ToString(CultureInfo.InvariantCulture);
    // JSON string literals emitted by System.Text.Json are also valid C# literals.
    private static string Quote(string? text) => text is null ? "null" : JsonSerializer.Serialize(text);
    private void Line(string line) => _source.Append("        ").Append(line).Append('\n');
}
