using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Globalization;
using System.Reflection;
using Jalium.UI.Controls;
using Jalium.UI.Controls.Primitives;
using Jalium.UI.Data;
using Jalium.UI.Input;
using Jalium.UI.Media;
using ControlsDataTemplateSelector = Jalium.UI.Controls.DataTemplateSelector;
using PrimitiveColumnHeader = Jalium.UI.Controls.Primitives.DataGridColumnHeader;

namespace Jalium.UI.Tests;

public sealed class DataGridRemainingWpfParityTests
{
    [Fact]
    public void DataGrid_DeclaresCommandsClipboardStylesConvertersAndResourceKeys()
    {
        AssertField<DataGrid, RoutedCommand>(nameof(DataGrid.BeginEditCommand));
        AssertField<DataGrid, RoutedCommand>(nameof(DataGrid.CancelEditCommand));
        AssertField<DataGrid, RoutedCommand>(nameof(DataGrid.CommitEditCommand));
        AssertField<DataGrid, DependencyProperty>(nameof(DataGrid.ClipboardCopyModeProperty));
        AssertField<DataGrid, DependencyProperty>(nameof(DataGrid.DragIndicatorStyleProperty));
        AssertField<DataGrid, DependencyProperty>(nameof(DataGrid.DropLocationIndicatorStyleProperty));

        Assert.Equal(typeof(RoutedUICommand), typeof(DataGrid).GetProperty(nameof(DataGrid.DeleteCommand))!.PropertyType);
        Assert.Equal(typeof(RoutedUICommand), typeof(DataGrid).GetProperty(nameof(DataGrid.SelectAllCommand))!.PropertyType);
        Assert.Equal(typeof(ComponentResourceKey), typeof(DataGrid).GetProperty(nameof(DataGrid.FocusBorderBrushKey))!.PropertyType);
        Assert.Equal(typeof(IValueConverter), typeof(DataGrid).GetProperty(nameof(DataGrid.HeadersVisibilityConverter))!.PropertyType);
        Assert.Equal(typeof(IValueConverter), typeof(DataGrid).GetProperty(nameof(DataGrid.RowDetailsScrollingConverter))!.PropertyType);

        var grid = new DataGrid();
        Assert.Equal(DataGridClipboardCopyMode.ExcludeHeader, grid.ClipboardCopyMode);
        grid.ClipboardCopyMode = DataGridClipboardCopyMode.IncludeHeader;
        Assert.Equal(DataGridClipboardCopyMode.IncludeHeader, grid.ClipboardCopyMode);
        Assert.Same(DataGrid.BeginEditCommand, DataGrid.BeginEditCommand);
        Assert.Same(DataGrid.FocusBorderBrushKey, DataGrid.FocusBorderBrushKey);
    }

    [Fact]
    public void DataGrid_DeclaresRemainingWpfMethodsAndEvents()
    {
        AssertMethod(typeof(DataGrid), nameof(DataGrid.BeginEdit), typeof(bool), isPublic: true,
            typeof(RoutedEventArgs));
        AssertMethod(typeof(DataGrid), nameof(DataGrid.ColumnFromDisplayIndex), typeof(DataGridColumn),
            isPublic: true, typeof(int));
        AssertMethod(typeof(DataGrid), nameof(DataGrid.GenerateColumns), typeof(Collection<DataGridColumn>),
            isPublic: true, typeof(IItemProperties));
        AssertMethod(typeof(DataGrid), nameof(DataGrid.ScrollIntoView), typeof(void), isPublic: true,
            typeof(object), typeof(DataGridColumn));

        foreach (var name in new[]
                 {
                     "OnAddingNewItem", "OnAutoGeneratedColumns", "OnAutoGeneratingColumn",
                     "OnCanExecuteBeginEdit", "OnCanExecuteCancelEdit", "OnCanExecuteCommitEdit",
                     "OnCanExecuteCopy", "OnCanExecuteDelete", "OnCopyingRowClipboardContent",
                     "OnExecutedBeginEdit", "OnExecutedCancelEdit", "OnExecutedCommitEdit",
                     "OnExecutedCopy", "OnExecutedDelete"
                 })
        {
            Assert.True(typeof(DataGrid).GetMethods(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
                .Single(method => method.Name == name).IsVirtual);
        }

        foreach (var name in new[]
                 {
                     "OnColumnDisplayIndexChanged", "OnColumnHeaderDragCompleted", "OnColumnHeaderDragDelta",
                     "OnColumnHeaderDragStarted", "OnColumnReordered", "OnColumnReordering"
                 })
        {
            var method = typeof(DataGrid).GetMethods(
                    BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
                .Single(candidate => candidate.Name == name);
            Assert.True(method.IsVirtual);
            Assert.True(method.IsFamilyOrAssembly);
        }

        Assert.Equal(typeof(EventHandler<AddingNewItemEventArgs>),
            typeof(DataGrid).GetEvent(nameof(DataGrid.AddingNewItem))!.EventHandlerType);
        Assert.Equal(typeof(EventHandler<DragStartedEventArgs>),
            typeof(DataGrid).GetEvent(nameof(DataGrid.ColumnHeaderDragStarted))!.EventHandlerType);
        Assert.Equal(typeof(EventHandler<DragDeltaEventArgs>),
            typeof(DataGrid).GetEvent(nameof(DataGrid.ColumnHeaderDragDelta))!.EventHandlerType);
        Assert.Equal(typeof(EventHandler<DragCompletedEventArgs>),
            typeof(DataGrid).GetEvent(nameof(DataGrid.ColumnHeaderDragCompleted))!.EventHandlerType);
        Assert.Equal(typeof(EventHandler<DataGridRowClipboardEventArgs>),
            typeof(DataGrid).GetEvent(nameof(DataGrid.CopyingRowClipboardContent))!.EventHandlerType);
        Assert.Equal(typeof(EventHandler<EventArgs>),
            typeof(DataGrid).GetEvent(nameof(DataGrid.CurrentCellChanged))!.EventHandlerType);
    }

    [Fact]
    public void GenerateColumns_UsesReportedItemMetadataAndDisplayIndexesAreValidated()
    {
        var descriptor = new object();
        var properties = new TestItemProperties(
        [
            new ItemPropertyInfo("Name", typeof(string), descriptor),
            new ItemPropertyInfo("Enabled", typeof(bool?), descriptor)
        ]);

        var columns = DataGrid.GenerateColumns(properties);
        Assert.Collection(columns,
            column => Assert.IsType<DataGridTextColumn>(column),
            column =>
            {
                var checkBox = Assert.IsType<DataGridCheckBoxColumn>(column);
                Assert.True(checkBox.IsThreeState);
            });
        Assert.All(columns, column => Assert.True(column.IsAutoGenerated));

        var grid = new DataGrid();
        grid.Columns.Add(columns[0]);
        grid.Columns.Add(columns[1]);
        Assert.Same(columns[0], grid.ColumnFromDisplayIndex(0));
        Assert.Same(columns[1], grid.ColumnFromDisplayIndex(1));
        Assert.Throws<ArgumentOutOfRangeException>(() => grid.ColumnFromDisplayIndex(-1));
        Assert.Throws<ArgumentOutOfRangeException>(() => grid.ColumnFromDisplayIndex(2));
    }

    [Fact]
    public void DataGridBoundAndConcreteColumns_ExposeDependencyPropertiesAndBindingBaseContracts()
    {
        AssertProperty<DataGridBoundColumn, BindingBase>(nameof(DataGridBoundColumn.Binding));
        AssertProperty<DataGridBoundColumn, Style>(nameof(DataGridBoundColumn.ElementStyle));
        AssertProperty<DataGridBoundColumn, Style>(nameof(DataGridBoundColumn.EditingElementStyle));
        AssertField<DataGridBoundColumn, DependencyProperty>(nameof(DataGridBoundColumn.ElementStyleProperty));
        AssertField<DataGridBoundColumn, DependencyProperty>(nameof(DataGridBoundColumn.EditingElementStyleProperty));

        foreach (var name in new[] { "FontFamily", "FontSize", "FontStyle", "FontWeight", "Foreground" })
        {
            AssertField<DataGridTextColumn, DependencyProperty>(name + "Property");
        }

        Assert.Equal(typeof(FontFamily), typeof(DataGridTextColumn).GetProperty(nameof(DataGridTextColumn.FontFamily))!.PropertyType);
        Assert.Equal(typeof(Jalium.UI.FontStyle), typeof(DataGridTextColumn).GetProperty(nameof(DataGridTextColumn.FontStyle))!.PropertyType);
        Assert.Equal(typeof(Jalium.UI.FontWeight), typeof(DataGridTextColumn).GetProperty(nameof(DataGridTextColumn.FontWeight))!.PropertyType);
        Assert.NotNull(DataGridTextColumn.DefaultElementStyle);
        Assert.NotNull(DataGridTextColumn.DefaultEditingElementStyle);

        AssertField<DataGridCheckBoxColumn, DependencyProperty>(nameof(DataGridCheckBoxColumn.IsThreeStateProperty));
        var checkBoxColumn = new DataGridCheckBoxColumn { IsThreeState = true };
        Assert.True(checkBoxColumn.IsThreeState);
        Assert.NotNull(DataGridCheckBoxColumn.DefaultElementStyle);
        Assert.NotNull(DataGridCheckBoxColumn.DefaultEditingElementStyle);
    }

    [Fact]
    public void ComboTemplateAndHyperlinkColumns_ExposeWpfBindingAndTemplateSurfaces()
    {
        Assert.Equal(typeof(DataGridColumn), typeof(DataGridComboBoxColumn).BaseType);
        foreach (var name in new[]
                 {
                     "DisplayMemberPathProperty", "EditingElementStyleProperty", "ElementStyleProperty",
                     "ItemsSourceProperty", "SelectedValuePathProperty"
                 })
        {
            AssertField<DataGridComboBoxColumn, DependencyProperty>(name);
        }

        AssertProperty<DataGridComboBoxColumn, BindingBase>(nameof(DataGridComboBoxColumn.SelectedItemBinding));
        AssertProperty<DataGridComboBoxColumn, BindingBase>(nameof(DataGridComboBoxColumn.SelectedValueBinding));
        AssertProperty<DataGridComboBoxColumn, BindingBase>(nameof(DataGridComboBoxColumn.TextBinding));
        Assert.Equal(typeof(BindingBase),
            typeof(DataGridComboBoxColumn).GetProperty(nameof(DataGridComboBoxColumn.ClipboardContentBinding))!.PropertyType);
        Assert.NotNull(DataGridComboBoxColumn.DefaultElementStyle);
        Assert.NotNull(DataGridComboBoxColumn.DefaultEditingElementStyle);
        Assert.NotNull(DataGridComboBoxColumn.TextBlockComboBoxStyleKey);

        foreach (var name in new[]
                 {
                     "CellEditingTemplateProperty", "CellEditingTemplateSelectorProperty",
                     "CellTemplateProperty", "CellTemplateSelectorProperty"
                 })
        {
            AssertField<DataGridTemplateColumn, DependencyProperty>(name);
        }

        AssertProperty<DataGridTemplateColumn, ControlsDataTemplateSelector>(nameof(DataGridTemplateColumn.CellTemplateSelector));
        AssertProperty<DataGridTemplateColumn, ControlsDataTemplateSelector>(nameof(DataGridTemplateColumn.CellEditingTemplateSelector));

        AssertField<DataGridHyperlinkColumn, DependencyProperty>(nameof(DataGridHyperlinkColumn.TargetNameProperty));
        AssertProperty<DataGridHyperlinkColumn, BindingBase>(nameof(DataGridHyperlinkColumn.ContentBinding));
        Assert.NotNull(DataGridHyperlinkColumn.DefaultElementStyle);
        Assert.NotNull(DataGridHyperlinkColumn.DefaultEditingElementStyle);
    }

    [Fact]
    public void TextAndComboColumns_ReadEditAndWriteThroughTheirBindings()
    {
        var model = new EditableRow { Name = "before", Choice = "two" };
        var textColumn = new ProbeTextColumn { Binding = new Binding(nameof(EditableRow.Name)) };
        var display = Assert.IsType<TextBlock>(textColumn.GenerateDisplay(model));
        Assert.Equal("before", display.Text);

        var textEditor = Assert.IsType<TextBox>(textColumn.GenerateEditor(model));
        textEditor.DataContext = model;
        Assert.Equal("before", textEditor.Text);
        textEditor.Text = "after";
        Assert.True(textColumn.Commit(textEditor));
        Assert.Equal("after", model.Name);

        var comboColumn = new ProbeComboColumn
        {
            ItemsSource = new[] { "one", "two" },
            SelectedItemBinding = new Binding(nameof(EditableRow.Choice))
        };
        var comboEditor = Assert.IsType<ComboBox>(comboColumn.GenerateEditor(model));
        comboEditor.DataContext = model;
        Assert.Equal("two", comboEditor.SelectedItem);
        comboEditor.SelectedItem = "one";
        Assert.True(comboColumn.Commit(comboEditor));
        Assert.Equal("one", model.Choice);
    }

    [Fact]
    public void ClipboardAndEventArgs_HaveWpfValueAndInheritanceSemantics()
    {
        var item = new object();
        var column = new DataGridTextColumn();
        var first = new DataGridClipboardCellContent(item, column, "value");
        var second = new DataGridClipboardCellContent(item, column, "value");
        Assert.Equal(first, second);
        Assert.True(first == second);
        Assert.False(first != second);
        Assert.Equal(first.GetHashCode(), second.GetHashCode());

        var rowArgs = new DataGridRowClipboardEventArgs(item, 0, 0, false);
        Assert.IsType<List<DataGridClipboardCellContent>>(rowArgs.ClipboardRowContent);

        Assert.Equal(typeof(EventArgs), typeof(DataGridColumnEventArgs).BaseType);
        Assert.Equal(typeof(DataGridColumnEventArgs), typeof(DataGridColumnReorderingEventArgs).BaseType);
        Assert.Equal(typeof(DataGridColumnEventArgs), typeof(DataGridSortingEventArgs).BaseType);
        Assert.Equal(typeof(EventArgs), typeof(DataGridPreparingCellForEditEventArgs).BaseType);

        var descriptor = new object();
        var autoArgs = new DataGridAutoGeneratingColumnEventArgs(column, "Name", typeof(string), descriptor);
        Assert.Same(descriptor, autoArgs.PropertyDescriptor);
    }

    [Fact]
    public void PresentersAndHeaders_ExposeContainerHooksReadOnlyStateAndResourceKeys()
    {
        Assert.Equal(typeof(ItemsControl), typeof(DataGridCellsPresenter).BaseType);
        Assert.Equal(typeof(ItemsControl), typeof(DataGridColumnHeadersPresenter).BaseType);
        Assert.True(typeof(VirtualizingPanel).IsAssignableFrom(typeof(DataGridCellsPanel)));

        foreach (var presenter in new[] { typeof(DataGridCellsPresenter), typeof(DataGridColumnHeadersPresenter) })
        {
            foreach (var methodName in new[]
                     {
                         "ClearContainerForItemOverride", "GetContainerForItemOverride",
                         "IsItemItsOwnContainerOverride", "PrepareContainerForItemOverride"
                     })
            {
                var method = presenter.GetMethods(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
                    .Single(candidate => candidate.Name == methodName);
                Assert.True(method.IsVirtual);
            }
        }

        var itemProperty = typeof(DataGridCellsPresenter).GetProperty(nameof(DataGridCellsPresenter.Item))!;
        Assert.True(itemProperty.GetMethod!.IsPublic);
        Assert.False(itemProperty.SetMethod!.IsPublic);

        foreach (var propertyName in new[] { "SortDirection", "CanUserSort", "DisplayIndex", "IsFrozen" })
        {
            var property = typeof(PrimitiveColumnHeader).GetProperty(propertyName)!;
            Assert.True(property.GetMethod!.IsPublic);
            Assert.False(property.SetMethod!.IsPublic);
        }

        Assert.False(typeof(DataGridRowHeader).GetProperty(nameof(DataGridRowHeader.IsRowSelected))!.SetMethod!.IsPublic);
        Assert.NotNull(PrimitiveColumnHeader.ColumnFloatingHeaderStyleKey);
        Assert.NotNull(PrimitiveColumnHeader.ColumnHeaderDropSeparatorStyleKey);

        foreach (var methodName in new[]
                 {
                     "OnCleanUpVirtualizedItem", "OnIsItemsHostChanged", "OnViewportSizeChanged"
                 })
        {
            Assert.True(typeof(DataGridRowsPresenter)
                .GetMethod(methodName, BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)!
                .IsVirtual);
        }
    }

    [Fact]
    public void HeaderAndRowDetailsConverters_ImplementWpfTemplateBehavior()
    {
        var culture = CultureInfo.InvariantCulture;
        Assert.Equal(Visibility.Visible, DataGrid.HeadersVisibilityConverter.Convert(
            DataGridHeadersVisibility.All, typeof(Visibility), DataGridHeadersVisibility.Column, culture));
        Assert.Equal(Visibility.Collapsed, DataGrid.HeadersVisibilityConverter.Convert(
            DataGridHeadersVisibility.Row, typeof(Visibility), DataGridHeadersVisibility.Column, culture));
        Assert.Equal(SelectiveScrollingOrientation.Vertical, DataGrid.RowDetailsScrollingConverter.Convert(
            true, typeof(SelectiveScrollingOrientation), SelectiveScrollingOrientation.Vertical, culture));
        Assert.Equal(SelectiveScrollingOrientation.Both, DataGrid.RowDetailsScrollingConverter.Convert(
            false, typeof(SelectiveScrollingOrientation), SelectiveScrollingOrientation.Vertical, culture));
    }

    private static void AssertField<TDeclaring, TField>(string name)
    {
        var field = typeof(TDeclaring).GetField(name, BindingFlags.Public | BindingFlags.Static)!;
        Assert.Equal(typeof(TField), field.FieldType);
    }

    private static void AssertProperty<TDeclaring, TProperty>(string name)
    {
        var property = typeof(TDeclaring).GetProperty(name, BindingFlags.Public | BindingFlags.Instance)!;
        Assert.Equal(typeof(TProperty), property.PropertyType);
        Assert.True(property.GetMethod!.IsPublic);
        Assert.True(property.SetMethod!.IsPublic);
    }

    private static void AssertMethod(
        Type declaringType,
        string name,
        Type returnType,
        bool isPublic,
        params Type[] parameterTypes)
    {
        var method = declaringType.GetMethod(
            name,
            BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance |
            BindingFlags.DeclaredOnly,
            binder: null,
            parameterTypes,
            modifiers: null)!;
        Assert.Equal(returnType, method.ReturnType);
        Assert.Equal(isPublic, method.IsPublic);
    }

    private sealed class TestItemProperties(IEnumerable<ItemPropertyInfo> properties) : IItemProperties
    {
        public ReadOnlyCollection<ItemPropertyInfo> ItemProperties { get; } =
            new(properties.ToList());
    }

    private sealed class EditableRow
    {
        public string Name { get; set; } = string.Empty;

        public string Choice { get; set; } = string.Empty;
    }

    private sealed class ProbeTextColumn : DataGridTextColumn
    {
        public FrameworkElement GenerateDisplay(object item) => GenerateElement(new DataGridCell(), item);

        public FrameworkElement GenerateEditor(object item) => GenerateEditingElement(new DataGridCell(), item);

        public bool Commit(FrameworkElement element) => CommitCellEdit(element);
    }

    private sealed class ProbeComboColumn : DataGridComboBoxColumn
    {
        public FrameworkElement GenerateEditor(object item) => GenerateEditingElement(new DataGridCell(), item);

        public bool Commit(FrameworkElement element) => CommitCellEdit(element);
    }
}
