"""Generate Unicode 18 context properties used by CSS full case mappings."""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path


VERSION = "18.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"
OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "src/managed/Jalium.UI.Controls/CssUnicodeCasingData.cs"
)
ENTRY = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z_]+)", re.M)


def read(filename: str) -> str:
    with urllib.request.urlopen(BASE + filename) as response:
        return response.read().decode("utf-8")


def property_set(source: str, name: str) -> set[int]:
    values: set[int] = set()
    for match in ENTRY.finditer(source):
        if match[3] != name:
            continue
        first = int(match[1], 16)
        last = int(match[2] or match[1], 16)
        values.update(range(first, last + 1))
    if not values:
        raise ValueError(f"Missing Unicode property: {name}")
    return values


def ranges(values: set[int]) -> list[tuple[int, int]]:
    result: list[tuple[int, int]] = []
    for value in sorted(values):
        if result and value == result[-1][1] + 1:
            result[-1] = result[-1][0], value
        else:
            result.append((value, value))
    return result


def field(name: str, values: set[int]) -> str:
    pairs = ranges(values)
    lines = [f"    private static readonly int[] {name} =", "    ["]
    for index in range(0, len(pairs), 4):
        chunk = pairs[index : index + 4]
        lines.append("        " + " ".join(
            f"0x{start:X}, 0x{end:X}," for start, end in chunk
        ))
    lines.append("    ];")
    return "\n".join(lines)


def main() -> None:
    unicode_data = read("UnicodeData.txt")
    above: set[int] = set()
    other_combining: set[int] = set()
    for line in unicode_data.splitlines():
        fields = line.split(";")
        combining_class = int(fields[3])
        if combining_class == 230:
            above.add(int(fields[0], 16))
        elif combining_class != 0:
            other_combining.add(int(fields[0], 16))

    prop_list = read("PropList.txt")
    derived = read("DerivedCoreProperties.txt")
    properties = {
        "s_above": above,
        "s_otherCombining": other_combining,
        "s_softDotted": property_set(prop_list, "Soft_Dotted"),
        "s_cased": property_set(derived, "Cased"),
        "s_caseIgnorable": property_set(derived, "Case_Ignorable"),
    }
    arrays = "\n\n".join(field(name, values) for name, values in properties.items())
    content = f"""// Generated by tools/generate-css-casing-context.py from Unicode {VERSION}.
// Data source: {BASE}UnicodeData.txt, PropList.txt, and DerivedCoreProperties.txt.
// Unicode data © 2026 Unicode, Inc. https://www.unicode.org/terms_of_use.html
namespace Jalium.UI.Controls;

internal static class CssUnicodeCasingData
{{
    internal static bool IsAbove(int codepoint) => Contains(s_above, codepoint);
    internal static bool IsOtherCombining(int codepoint) => Contains(s_otherCombining, codepoint);
    internal static bool IsSoftDotted(int codepoint) => Contains(s_softDotted, codepoint);
    internal static bool IsCased(int codepoint) => Contains(s_cased, codepoint);
    internal static bool IsCaseIgnorable(int codepoint) => Contains(s_caseIgnorable, codepoint);

    private static bool Contains(int[] ranges, int value)
    {{
        var low = 0;
        var high = ranges.Length / 2 - 1;
        while (low <= high)
        {{
            var middle = low + (high - low) / 2;
            var start = ranges[middle * 2];
            var end = ranges[middle * 2 + 1];
            if (value < start) high = middle - 1;
            else if (value > end) low = middle + 1;
            else return true;
        }}
        return false;
    }}

{arrays}
}}
"""
    OUTPUT.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
