"""Embed the shared HLSL for native pipelines compiled from in-memory source."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = root / "src/native/jalium.native.core/shaders/elliptical_clip.hlsli"
target = root / "src/native/jalium.native.core/include/jalium_elliptical_clip_shader.h"
shader = source.read_text(encoding="utf-8")
target.write_text(
    '// Generated by tools/generate-elliptical-clip-shader.py. Do not edit.\n'
    '#pragma once\nnamespace jalium {\n'
    'inline constexpr char kEllipticalClipHlsl[] = R"JALIUM(\n'
    + shader + ')JALIUM";\n}\n', encoding="utf-8", newline="\n")
