"""Regenerate Unicode classes used by CSS Text line breaking and autospace."""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path


VERSION = "18.0.0"
BASE = f"https://www.unicode.org/Public/{VERSION}/ucd/"
OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "src/managed/Jalium.UI.Controls/CssUnicodeLineBreakData.cs"
)
ENTRY = re.compile(r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z0-9]+)", re.M)
ENTRY_SET = re.compile(
    r"^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*([A-Za-z0-9]+(?:[ \t]+[A-Za-z0-9]+)*)",
    re.M,
)


def read_property(filename: str) -> dict[int, str]:
    with urllib.request.urlopen(BASE + filename) as response:
        source = response.read().decode("utf-8")
    values: dict[int, str] = {}
    for match in ENTRY.finditer(source):
        first = int(match[1], 16)
        last = int(match[2] or match[1], 16)
        values.update((codepoint, match[3]) for codepoint in range(first, last + 1))
    return values


def read_property_set(filename: str) -> dict[int, set[str]]:
    with urllib.request.urlopen(BASE + filename) as response:
        source = response.read().decode("utf-8")
    values: dict[int, set[str]] = {}
    for match in ENTRY_SET.finditer(source):
        first = int(match[1], 16)
        last = int(match[2] or match[1], 16)
        scripts = set(match[3].split())
        values.update((codepoint, scripts) for codepoint in range(first, last + 1))
    return values


def merged_ranges(codepoints: set[int]) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    for codepoint in sorted(codepoints):
        if ranges and codepoint == ranges[-1][1] + 1:
            ranges[-1] = ranges[-1][0], codepoint
        else:
            ranges.append((codepoint, codepoint))
    return ranges


def field(name: str, codepoints: set[int]) -> str:
    pairs = merged_ranges(codepoints)
    lines = [f"    private static readonly int[] {name} =", "    ["]
    for index in range(0, len(pairs), 4):
        chunk = pairs[index : index + 4]
        lines.append(
            "        "
            + " ".join(f"0x{start:X}, 0x{end:X}," for start, end in chunk)
        )
    lines.append("    ];")
    return "\n".join(lines)


def main() -> None:
    line_break = read_property("LineBreak.txt")
    east_asian_width = read_property("EastAsianWidth.txt")
    scripts = read_property("Scripts.txt")
    script_extensions = read_property_set("ScriptExtensions.txt")
    han = {cp for cp, value in scripts.items() if value == "Han"}
    for codepoint, values in script_extensions.items():
        if "Hani" in values:
            han.add(codepoint)
        else:
            han.discard(codepoint)
    wide = {"A", "F", "W"}
    properties = {
        "s_ideographic": {cp for cp, value in line_break.items() if value == "ID"},
        "s_hanExtendedScript": han,
        "s_eastAsianWideOrFullwidth": {
            cp for cp, value in east_asian_width.items() if value in {"W", "F"}
        },
        "s_eastAsianFullwidth": {
            cp for cp, value in east_asian_width.items() if value == "F"
        },
        "s_conditionalJapanese": {cp for cp, value in line_break.items() if value == "CJ"},
        "s_inseparable": {cp for cp, value in line_break.items() if value == "IN"},
        "s_widePostfix": {
            cp for cp, value in line_break.items()
            if value == "PO" and east_asian_width.get(cp) in wide
        },
        "s_widePrefix": {
            cp for cp, value in line_break.items()
            if value == "PR" and east_asian_width.get(cp) in wide
        },
    }
    arrays = "\n\n".join(field(name, values) for name, values in properties.items())
    content = f"""// Generated by tools/generate-css-linebreak-unicode.py from Unicode {VERSION}.
// Data source: {BASE}LineBreak.txt, EastAsianWidth.txt, Scripts.txt, and ScriptExtensions.txt.
// Unicode data © 2026 Unicode, Inc. https://www.unicode.org/terms_of_use.html
using System.Text;

namespace Jalium.UI.Controls;

internal static class CssUnicodeLineBreakData
{{
    internal static bool IsIdeographic(Rune rune) => Contains(s_ideographic, rune.Value);
    internal static bool IsHanExtendedScript(Rune rune) => Contains(s_hanExtendedScript, rune.Value);
    internal static bool IsEastAsianWideOrFullwidth(Rune rune) => Contains(s_eastAsianWideOrFullwidth, rune.Value);
    internal static bool IsEastAsianFullwidth(Rune rune) => Contains(s_eastAsianFullwidth, rune.Value);
    internal static bool IsConditionalJapanese(Rune rune) => Contains(s_conditionalJapanese, rune.Value);
    internal static bool IsInseparable(Rune rune) => Contains(s_inseparable, rune.Value);
    internal static bool IsWidePostfix(Rune rune) => Contains(s_widePostfix, rune.Value);
    internal static bool IsWidePrefix(Rune rune) => Contains(s_widePrefix, rune.Value);

    private static bool Contains(int[] ranges, int value)
    {{
        var low = 0;
        var high = ranges.Length / 2 - 1;
        while (low <= high)
        {{
            var middle = low + (high - low) / 2;
            var start = ranges[middle * 2];
            var end = ranges[middle * 2 + 1];
            if (value < start) high = middle - 1;
            else if (value > end) low = middle + 1;
            else return true;
        }}
        return false;
    }}

{arrays}
}}
"""
    OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    print(f"Generated {OUTPUT}")


if __name__ == "__main__":
    main()
