"""Generate the IANA alias and extlang tables used by CSS :lang().

The registry snapshot is pinned by date and SHA-256 so updates are deliberate.
Runtime language matching uses only the checked-in C# data file.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from urllib.request import urlopen


URL = "https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry"
FILE_DATE = "2026-09-17"
SHA256 = "755fad43283be7b41ebe3c89ad054b6eaf928f404f9c0edb74799e0eab74beb1"
OUTPUT = Path(__file__).resolve().parents[1] / (
    "src/managed/Jalium.UI.Core/Css/CssLanguageTagData.g.cs"
)


def records(text: str) -> list[dict[str, str]]:
    result = []
    for block in text.split("%%"):
        fields: dict[str, str] = {}
        last = ""
        for line in block.splitlines():
            if line.startswith(" ") and last:
                fields[last] += " " + line.strip()
            elif ": " in line:
                last, value = line.split(": ", 1)
                if last in fields:
                    if last in {"Type", "Subtag", "Tag", "Preferred-Value"} or (
                        last == "Prefix" and fields.get("Type") == "extlang"
                    ):
                        raise ValueError(f"repeated registry field {last}")
                    continue
                fields[last] = value
        if "Type" in fields:
            result.append(fields)
    return result


def write_map(lines: list[str], name: str, values: dict[str, str]) -> None:
    lines.append(f"    internal static readonly Dictionary<string, string> {name} = new(StringComparer.Ordinal)\n    {{")
    for key, value in sorted(values.items()):
        lines.append(f"        [{json.dumps(key)}] = {json.dumps(value)},")
    lines.append("    };\n")


def main() -> None:
    with urlopen(URL, timeout=30) as response:
        data = response.read()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SHA256:
        raise ValueError(f"IANA registry changed: expected {SHA256}, got {digest}")
    text = data.decode("utf-8")
    if not text.startswith(f"File-Date: {FILE_DATE}\n"):
        raise ValueError("unexpected IANA registry date")

    maps: dict[str, dict[str, str]] = {
        "TagAliases": {},
        "LanguageAliases": {},
        "RegionAliases": {},
        "VariantAliases": {},
        "ExtlangPrefixes": {},
    }
    for record in records(text):
        kind = record["Type"]
        key = record.get("Subtag", record.get("Tag", "")).lower()
        preferred = record.get("Preferred-Value", "").lower()
        if kind in ("grandfathered", "redundant") and preferred:
            target = maps["TagAliases"]
        elif kind == "language" and preferred:
            target = maps["LanguageAliases"]
        elif kind == "region" and preferred:
            target = maps["RegionAliases"]
        elif kind == "variant" and preferred:
            target = maps["VariantAliases"]
        elif kind == "extlang":
            if preferred != key or "Prefix" not in record:
                raise ValueError(f"unexpected extlang record: {record}")
            preferred = record["Prefix"].lower()
            target = maps["ExtlangPrefixes"]
        else:
            continue
        if not key or key in target:
            raise ValueError(f"duplicate or empty {kind} key: {key}")
        target[key] = preferred

    lines = [
        "// Generated by tools/generate-css-language-tags.py from the IANA Language Subtag Registry.",
        f"// File-Date: {FILE_DATE}; SHA-256: {SHA256}",
        f"// {URL}",
        "namespace Jalium.UI.Styling;",
        "",
        "internal static class CssLanguageTagData",
        "{",
    ]
    for name, values in maps.items():
        write_map(lines, name, values)
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
