#!/usr/bin/env python3
"""Fail when Metal silently inherits a D3D12 parity-required virtual.

This is intentionally source-only so it runs on Windows/Linux before an Apple
SDK is available. Runtime/pixel tests remain the authority for implementation
quality; this guard prevents a newly added D3D12 override from being forgotten.
"""

from __future__ import annotations

import pathlib
import re
import sys
import argparse

ROOT = pathlib.Path(__file__).resolve().parents[1]
D3D_HEADERS = [
    ROOT / "src/native/jalium.native.d3d12/include/d3d12_backend.h",
    ROOT / "src/native/jalium.native.d3d12/include/d3d12_render_target.h",
]
METAL_HEADER = ROOT / "src/native/jalium.native.metal/include/metal_backend.h"
METAL_SOURCES = list((ROOT / "src/native/jalium.native.metal/src").glob("*.cpp"))

# Declaration parity alone can be defeated by an override whose body is a
# default return. These markers are deliberately implementation-shaped: every
# critical capability must retain the GPU/resource mechanism that gives the
# override its cross-platform semantics.
REQUIRED_IMPLEMENTATION_MARKERS = {
    "device/frame ring": ("dispatch_semaphore_create(kFrameCount)", "newSharedEvent"),
    "fence-gated heaps": ("newHeapWithDescriptor", "MTLStorageModeMemoryless"),
    "CAMetalLayer present": ("nextDrawable", "presentDrawable"),
    "persistent damage": ("dirtyRects", "textureReplacePipeline"),
    "nested stencil clip": ("EncodeStencilStack", "jalium_clip_stencil_fragment"),
    "Impeller paths": ("TriangulateCompoundPath", "ExpandStrokePath"),
    "Vello graph": ("StageCount", "dispatch(Fine"),
    "CoreText cache": ("CTLineDraw", "textCache"),
    "bitmap mipmaps": ("mipmapLevelCount", "MTLSamplerMipFilterLinear"),
    "effects": ("DrawBackdropMaterial", "DrawLiquidGlass"),
    "SourceHlsl": ("CompileMetalPixelShader", "JALIUM_HAS_DXC_SPIRV_CROSS"),
    "Ink BrushMain": ("CompileMetalBrushShader", "kSharedBrushPixelPreamble"),
    "external video": ("CVMetalTextureCacheCreateTextureFromImage", "RetainForCommandBuffer"),
    "two-phase readback": ("RequestReadback", "FetchReadback"),
}

# Backend-specific handles/race injectors have no Metal semantic counterpart.
# Their cross-platform behavior is covered by Metal's display-link pacing and
# simulated device-loss/resource-retirement tests instead.
ALLOWED_D3D12_ONLY = {
    "GetFrameLatencyWaitable",
    "DebugForceLeakedCommandListResize",
    "DebugForceVelloOutputOrphan",
}


def overrides(path: pathlib.Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)
    text = re.sub(r"//[^\n]*", " ", text)
    pattern = re.compile(
        r"(?<!~)\b([A-Za-z_]\w*)\s*\((?:[^(){};]|\([^(){};]*\))*\)\s*"
        r"(?:const\s*)?(?:noexcept\s*)?override\b",
        re.S,
    )
    return {match.group(1) for match in pattern.finditer(text)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-report", action="store_true")
    args = parser.parse_args()
    d3d: set[str] = set()
    for header in D3D_HEADERS:
        d3d |= overrides(header)
    metal = overrides(METAL_HEADER)
    missing = sorted(d3d - metal - ALLOWED_D3D12_ONLY)
    extra = sorted(metal - d3d)
    print(f"D3D12 overrides: {len(d3d)}")
    print(f"Metal overrides: {len(metal)}")
    if extra:
        print("Metal-specific/additional overrides: " + ", ".join(extra))
    if missing:
        print("ERROR: parity-required D3D12 overrides missing in Metal:", file=sys.stderr)
        for name in missing:
            print(f"  - {name}", file=sys.stderr)
        return 1
    implementation = "\n".join(path.read_text(encoding="utf-8") for path in METAL_SOURCES)
    marker_failures = [
        f"{capability}: missing {', '.join(marker for marker in markers if marker not in implementation)}"
        for capability, markers in REQUIRED_IMPLEMENTATION_MARKERS.items()
        if any(marker not in implementation for marker in markers)
    ]
    if marker_failures:
        print("ERROR: Metal critical implementations regressed:", file=sys.stderr)
        for failure in marker_failures:
            print(f"  - {failure}", file=sys.stderr)
        return 1
    if args.write_report:
        report = ROOT / "docs/metal-d3d12-capabilities.generated.md"
        lines = [
            "# D3D12 → Metal generated capability surface",
            "",
            "Generated by `python tools/metal_parity_check.py --write-report`.",
            "The baseline is checkpoint `91c3242d`; declaration coverage is",
            "supplemented by the critical GPU-mechanism checks in the generator.",
            "",
            "| Render capability virtual | Metal status |",
            "|---|---|",
        ]
        for name in sorted(d3d):
            status = "Apple-equivalent (no HANDLE/native D3D race object)" \
                if name in ALLOWED_D3D12_ONLY else "Implemented override"
            lines.append(f"| `{name}` | {status} |")
        lines.append("")
        report.write_text("\n".join(lines), encoding="utf-8", newline="\n")
        print(f"Wrote {report.relative_to(ROOT)}")
    print("PASS: Metal declares every cross-platform D3D12 capability.")
    print("PASS: Metal critical overrides retain their GPU implementation mechanisms.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
