# Regenerates the pre-compiled D3D12 Vello compute DXBC header
# (../include/d3d12_vello_bytecode.h) from the canonical HLSL sources in this
# directory (vello_*.cs.hlsl + vello_shared.hlsli).
#
# These are the SAME canonical sources the Vulkan backend compiles to SPIR-V
# via jalium.native.vulkan/shaders/gen_vello_spv.ps1. Whenever any vello_*
# shader changes, re-run BOTH generators so the two GPU backends stay in
# lockstep on the PTCL command layout (e.g. write_grad's 8-word gradient
# contract shared by vello_coarse.cs.hlsl and vello_fine.cs.hlsl).
#
# Compiles with fxc (Windows SDK) /T cs_5_1 /E main /O3 - the same profile as
# the original header (verified via the DXBC SHEX version tokens: all 13
# stages are sm5.1 compute).
#
# Usage:  powershell ./gen_vello_bytecode.ps1   (run from anywhere; paths are script-relative)

param(
    [string]$ShaderSrcDir = $PSScriptRoot,
    [string]$OutDir = (Join-Path $PSScriptRoot 'compiled'),
    [string]$HeaderPath = (Join-Path $PSScriptRoot '..\include\d3d12_vello_bytecode.h'),
    [string]$FxcPath = ''
)

$ErrorActionPreference = 'Stop'

# Resolve fxc.exe: explicit -FxcPath > newest Windows SDK > PATH.
$fxc = $null
if ($FxcPath) {
    if (-not (Test-Path $FxcPath)) { throw "fxc not found at -FxcPath '$FxcPath'" }
    $fxc = $FxcPath
} else {
    $kitsRoot = Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10\bin'
    if (Test-Path $kitsRoot) {
        $candidates = Get-ChildItem $kitsRoot -Directory |
            Where-Object { $_.Name -match '^10\.' -and (Test-Path (Join-Path $_.FullName 'x64\fxc.exe')) } |
            Sort-Object { [version]$_.Name } -Descending
        if ($candidates) { $fxc = Join-Path $candidates[0].FullName 'x64\fxc.exe' }
    }
    if (-not $fxc) {
        $cmd = Get-Command fxc -ErrorAction SilentlyContinue
        if ($cmd) { $fxc = $cmd.Source }
    }
}
if (-not $fxc) { throw 'fxc.exe not found (install a Windows 10/11 SDK or pass -FxcPath)' }
Write-Host "Using fxc: $fxc"

# The 13 Vello compute stages, in the header's array order.
# Symbol names MUST stay in sync with the consumers in d3d12_vello.cpp
# (CreateComputePipelines / CreateGpuPipelines reference vello_bytecode::k*).
$stages = @(
    @{ File = 'vello_bbox_clear';        Symbol = 'kBboxClear' },
    @{ File = 'vello_flatten';           Symbol = 'kFlatten' },
    @{ File = 'vello_clip_reduce';       Symbol = 'kVelloClipReduce' },
    @{ File = 'vello_clip_leaf';         Symbol = 'kVelloClipLeaf' },
    @{ File = 'vello_binning';           Symbol = 'kBinning' },
    @{ File = 'vello_tile_alloc';        Symbol = 'kTileAlloc' },
    @{ File = 'vello_path_count_setup';  Symbol = 'kPathCountSetup' },
    @{ File = 'vello_path_count';        Symbol = 'kPathCount' },
    @{ File = 'vello_backdrop';          Symbol = 'kBackdrop' },
    @{ File = 'vello_coarse';            Symbol = 'kCoarse' },
    @{ File = 'vello_path_tiling_setup'; Symbol = 'kPathTilingSetup' },
    @{ File = 'vello_path_tiling';       Symbol = 'kPathTiling' },
    @{ File = 'vello_fine';              Symbol = 'kFine' }
)

if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir | Out-Null }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('// Auto-generated pre-compiled Vello GPU compute shader bytecode.')
[void]$sb.AppendLine('// Eliminates runtime D3DCompile.')
[void]$sb.AppendLine('// Generated by shaders/gen_vello_bytecode.ps1 (fxc /T cs_5_1 /E main /O3) - do not edit manually.')
[void]$sb.AppendLine('// Source of truth: shaders/vello_*.cs.hlsl + vello_shared.hlsli, shared with the Vulkan')
[void]$sb.AppendLine('// backend (jalium.native.vulkan/shaders/gen_vello_spv.ps1) - regenerate both together.')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace vello_bytecode {')

foreach ($stage in $stages) {
    $name = $stage.File
    $sym = $stage.Symbol
    $src = Join-Path $ShaderSrcDir "$name.cs.hlsl"
    if (-not (Test-Path $src)) { throw "Missing shader source: $src" }
    $cso = Join-Path $OutDir "$name.cs.cso"

    Write-Host "Compiling $name.cs.hlsl -> compiled/$name.cs.cso"
    & $fxc /nologo /T cs_5_1 /E main /O3 /I $ShaderSrcDir /Fo $cso $src
    if ($LASTEXITCODE -ne 0) { throw "fxc failed for $name (exit $LASTEXITCODE)" }

    $bytes = [System.IO.File]::ReadAllBytes($cso)

    [void]$sb.AppendLine()
    [void]$sb.AppendLine("// $name.cs.hlsl ($($bytes.Length) bytes)")
    [void]$sb.AppendLine("static const unsigned char ${sym}[] = {")
    for ($i = 0; $i -lt $bytes.Length; $i += 16) {
        $n = [Math]::Min(16, $bytes.Length - $i)
        $hex = for ($j = 0; $j -lt $n; $j++) { '0x{0:x2}' -f $bytes[$i + $j] }
        $line = '    ' + ($hex -join ', ')
        if ($i + $n -lt $bytes.Length) { $line += ',' }
        [void]$sb.AppendLine($line)
    }
    [void]$sb.AppendLine('};')
    [void]$sb.AppendLine("static const unsigned int ${sym}Size = sizeof(${sym});")
}

[void]$sb.AppendLine()
[void]$sb.AppendLine('} // namespace vello_bytecode')

[System.IO.File]::WriteAllText($HeaderPath, $sb.ToString())
Write-Host "Generated $HeaderPath ($([System.IO.FileInfo]::new($HeaderPath).Length) bytes)"
